name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Compile tests
      run: javac "jsoup-1.13.1.jar" "src/main/java/com/giua/testclasses/TestClasses.java src/main/java/com/giua/objects/*.java" "src/main/java/com/giua/webscraper/GiuaScraper.java" "src/main/java/com/giua/webscraper/GiuaScraperExceptions.java"
      #${{ secrets.GS_USER_LOGIN }} ${{ secrets.GS_PASSWORD_LOGIN }} false
    
    
    
    
